### ISSUE TITLE
Installation Failure - message=Corrupt source

### ISSUE THREAD

**Issue by dpfontaine** [YunoHost-Apps/bitwarden_ynh#131]
Hi, 
I tried to install bitwarden  on the app from the webadmin. The process was stopped due to a corrupted source. That's the issue

### Describe the bug
Message shown after trying to install bitwarden 
"L’opération 'Installer l’application 'bitwarden'' a échoué ! Pour obtenir de l’aide, merci de partager le journal de l’opération en cliquant ici"

### Context
- Hardware: Raspberry Pi 4 (2GB RAM 128 GB USB Stick) at home 
- YunoHost version:  4.1.8 (stable).
- I have access to my server: Through the webadmin and Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Steps to reproduce
I've used the webadmin, Applications > Installer > Toutes les applications > then searching for "bitwarden", then Installer

### Expected behavior
I was expecting the installation to be completed :)

### Logs

2021-04-27 20:10:59,244: DEBUG - + local local_src=/opt/yunohost-apps-src/bitwarden/app.tar.gz
2021-04-27 20:10:59,245: DEBUG - + test -e /opt/yunohost-apps-src/bitwarden/app.tar.gz
2021-04-27 20:10:59,245: DEBUG - ++ wget --tries 3 --no-dns-cache --timeout 900 --no-verbose --output-document=app.tar.gz https://github.com/dani-garcia/bitwarden_rs/archive/1.20.0.tar.gz
2021-04-27 20:11:01,451: DEBUG - + out='2021-04-27 20:11:01 URL:https://codeload.github.com/dani-garcia/vaultwarden/tar.gz/1.20.0 [439967/439967] -> "app.tar.gz" [1]'
2021-04-27 20:11:01,453: DEBUG - + echo '96fc0c3d55ed770af7209f881e107c33cf8ddf5179c504eacbc155dcb0f28641e5d28dd9cbd4f071540a7aac3d0e40b519de1fb85a523c6b74fb91a930d329a8 app.tar.gz'
2021-04-27 20:11:01,454: DEBUG - + sha512sum --check --status
2021-04-27 20:11:01,455: DEBUG - + ynh_die '--message=Corrupt source'
2021-04-27 20:11:01,559: DEBUG - + ret_code=1
2021-04-27 20:11:01,561: WARNING - Corrupt source
2021-04-27 20:11:01,562: DEBUG - + echo 'Corrupt source'
2021-04-27 20:11:01,563: DEBUG - + exit 1
2021-04-27 20:11:01,563: DEBUG - + ynh_exit_properly
2021-04-27 20:11:01,564: DEBUG - + local exit_code=1
2021-04-27 20:11:01,564: DEBUG - + '[' 1 -eq 0 ']'
2021-04-27 20:11:01,565: DEBUG - + trap '' EXIT
2021-04-27 20:11:01,565: DEBUG - + set +o errexit
2021-04-27 20:11:01,565: DEBUG - + set +o nounset
2021-04-27 20:11:01,566: DEBUG - + sleep 0.5
2021-04-27 20:11:02,070: DEBUG - + type -t ynh_clean_setup
2021-04-27 20:11:02,071: DEBUG - + ynh_clean_setup
2021-04-27 20:11:02,072: DEBUG - + ynh_clean_check_starting
2021-04-27 20:11:02,073: DEBUG - + '[' -n '' ']'
2021-04-27 20:11:02,073: DEBUG - + '[' -n '' ']'
2021-04-27 20:11:02,074: DEBUG - + exit 1
2021-04-27 20:11:02,138: ERROR - Impossible d’installer bitwarden : Une erreur est survenue dans le script d’installation de l’application

Thanks for your help.

**Comment by seiya74656** [comment]
I've got the same problem. last week there was no problem on installing, this problem must be new.

**Comment by alexAubin** [comment]
Issue reported here: https://github.com/dani-garcia/vaultwarden/issues/1628

to make sure it's not a malicious actor updating the archive somehow

**Comment by ericgaspar** [comment]
#132 should fix the shasum

**Comment by alexAubin** [comment]
c.f discussion with bitwarden / vaultwarden folks: the issue is due to a repo name change which for some reason triggered a rebuild of a the .tar.gz archive on github's side

**Comment by trogeat** [comment]
Merge of https://github.com/YunoHost-Apps/bitwarden_ynh/pull/132 fixed the problem for me with a fresh install.

**Comment by grigri007** [comment]
same problem for instalation

**Comment by dpfontaine** [comment]
Issue still occuring, after having done the update for the system packages and the applications.
Should I do something else?

**Logs**

2021-04-29 13:53:13,207: DEBUG - + local local_src=/opt/yunohost-apps-src/bitwarden/app.tar.gz
2021-04-29 13:53:13,207: DEBUG - + test -e /opt/yunohost-apps-src/bitwarden/app.tar.gz
2021-04-29 13:53:13,208: DEBUG - ++ wget --tries 3 --no-dns-cache --timeout 900 --no-verbose --output-document=app.tar.gz https://github.com/dani-garcia/bitwarden_rs/archive/1.20.0.tar.gz
2021-04-29 13:53:14,411: DEBUG - + out='2021-04-29 13:53:14 URL:https://codeload.github.com/dani-garcia/vaultwarden/tar.gz/1.20.0 [439967/439967] -> "app.tar.gz" [1]'
2021-04-29 13:53:14,412: DEBUG - + echo '96fc0c3d55ed770af7209f881e107c33cf8ddf5179c504eacbc155dcb0f28641e5d28dd9cbd4f071540a7aac3d0e40b519de1fb85a523c6b74fb91a930d329a8 app.tar.gz'
2021-04-29 13:53:14,413: DEBUG - + sha512sum --check --status
2021-04-29 13:53:14,514: DEBUG - + ynh_die '--message=Corrupt source'
2021-04-29 13:53:14,519: WARNING - Corrupt source
2021-04-29 13:53:14,520: DEBUG - + ret_code=1
2021-04-29 13:53:14,521: DEBUG - + echo 'Corrupt source'
2021-04-29 13:53:14,522: DEBUG - + exit 1
2021-04-29 13:53:14,522: DEBUG - + ynh_exit_properly
2021-04-29 13:53:14,522: DEBUG - + local exit_code=1
2021-04-29 13:53:14,523: DEBUG - + '[' 1 -eq 0 ']'
2021-04-29 13:53:14,523: DEBUG - + trap '' EXIT
2021-04-29 13:53:14,524: DEBUG - + set +o errexit
2021-04-29 13:53:14,524: DEBUG - + set +o nounset
2021-04-29 13:53:14,525: DEBUG - + sleep 0.5
2021-04-29 13:53:15,026: DEBUG - + type -t ynh_clean_setup
2021-04-29 13:53:15,028: DEBUG - + ynh_clean_setup
2021-04-29 13:53:15,029: DEBUG - + ynh_clean_check_starting
2021-04-29 13:53:15,029: DEBUG - + '[' -n '' ']'
2021-04-29 13:53:15,030: DEBUG - + '[' -n '' ']'
2021-04-29 13:53:15,032: DEBUG - + exit 1
2021-04-29 13:53:15,160: ERROR - Impossible d’installer bitwarden : Une erreur est survenue dans le script d’installation de l’application

**Comment by yalh76** [comment]
You are still on the old checksum =>
https://github.com/YunoHost-Apps/bitwarden_ynh/commit/36afe70c2fa62f6cdc6290cdbbceabfc64542984

Wait a few hours and try to update.
